CREATE TABLE SALESTAXES.PRODUCTTYPES
(
  ID_PRODUCT_TYPE      NUMBER(16)          NOT NULL,
  NAME                 VARCHAR2(25 CHAR)   NOT NULL,
  TAX_ID               NUMBER(16)          NOT NULL
);
CREATE UNIQUE INDEX SALESTAXES.IDX_PRODUCTTYPES ON SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE);
ALTER TABLE SALESTAXES.PRODUCTTYPES ADD (CONSTRAINT PRODUCTTYPES_PK PRIMARY KEY (ID_PRODUCT_TYPE));
ALTER TABLE SALESTAXES.PRODUCTTYPES ADD (CONSTRAINT FK_PRODUCTTYPES_TAXES FOREIGN KEY (TAX_ID) REFERENCES SALESTAXES.TAXES (ID_TAX) ON DELETE CASCADE);