INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (1, 'GOOD', 2);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (2, 'IMPORTED GOOD', 4);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (3, 'BOOK', 1);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (4, 'IMPORTED BOOK', 3);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (5, 'FOOD', 1);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (6, 'IMPORTED FOOD', 3);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (7, 'MEDICAL', 1);
INSERT INTO SALESTAXES.PRODUCTTYPES (ID_PRODUCT_TYPE, NAME, TAX_ID) VALUES (8, 'IMPORTED MEDICAL', 3);